# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=5)),
                ('red', models.CharField(max_length=5)),
                ('green', models.CharField(max_length=5)),
                ('blue', models.CharField(max_length=5)),
                ('length', models.CharField(max_length=5)),
                ('width', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawdata', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
