# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171027_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adj',
            name='source',
        ),
        migrations.RemoveField(
            model_name='adj',
            name='target',
        ),
        migrations.RemoveField(
            model_name='adj',
            name='value',
        ),
        migrations.RemoveField(
            model_name='node',
            name='area',
        ),
        migrations.RemoveField(
            model_name='node',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='node',
            name='green',
        ),
        migrations.RemoveField(
            model_name='node',
            name='length',
        ),
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='number',
        ),
        migrations.RemoveField(
            model_name='node',
            name='red',
        ),
        migrations.RemoveField(
            model_name='node',
            name='width',
        ),
        migrations.AddField(
            model_name='adj',
            name='adjString',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='nodeString',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='rawdata',
            field=models.CharField(max_length=5000),
        ),
    ]
